#
# This docker-compose file is usable for demo purposes:
#
version: '3.4'
services:

  loginbuddy-democlient:
    image: saschazegerman/loginbuddy-democlient:latest
    container_name: democlient
    restart: always
    hostname: democlient.loginbuddy.net
    ports:
      - "80:80"
      - "443:443"
    environment:
      - "SSL_PWD=${SSL_PWD}"
      - "LOGINBUDDY_SIDECAR_LOCATION=http://loginbuddy-sidecar:8044"
    volumes:
      - ./dev/loginbuddy.p12:/usr/local/tomcat/ssl/loginbuddy.p12

  loginbuddy-demoserver:
    image: saschazegerman/loginbuddy-demoserver:latest
    container_name: demoserver
    restart: always
    hostname: demoserver.loginbuddy.net
    ports:
      - "8443:8443"
    environment:
      - "SSL_PWD=${SSL_PWD}"
    volumes:
      - ./dev/loginbuddy.p12:/usr/local/tomcat/ssl/loginbuddy.p12

  loginbuddy:
    image: saschazegerman/loginbuddy:latest
    container_name: loginbuddy
    restart: always
    hostname: local.loginbuddy.net
    depends_on:
      - loginbuddy-demoserver
    ports:
      - "8000:8000"
      - "8444:8444"
    volumes:
      - ./docker-build/add-ons/loginbuddy/permissions.policy:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/permissions.policy
      - ./docker-build/add-ons/loginbuddy/config.json:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/config.json
      - ./docker-build/add-ons/loginbuddy/discovery.json:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/discovery.json
      - ./docker-build/add-ons/loginbuddy/server_loginbuddy.png:/usr/local/tomcat/webapps/ROOT/images/server_loginbuddy.png
      - ./docker-build/add-ons/loginbuddy/server_dynamic.png:/usr/local/tomcat/webapps/ROOT/images/server_dynamic.png
      - ./dev/loginbuddy.p12:/usr/local/tomcat/ssl/loginbuddy.p12
    environment:
      - "SSL_PWD=${SSL_PWD}"
      - "SSL_PORT=8444"
      - "SUPPORT_OIDCDR=true"
      - "SSL_TRUSTED_SERVER=loginbuddy-demoserver:8443"
      - "HOSTNAME_LOGINBUDDY=local.loginbuddy.net"
#      - "HAZELCAST=hazelcast1:5701,hazelcast2:5701"

  loginbuddy-sidecar:
    image: saschazegerman/loginbuddy-sidecar:latest
    container_name: loginbuddy-sidecar
    hostname: loginbuddy-sidecar
    restart: always
    depends_on:
      - loginbuddy-demoserver
    environment:
      - "SUPPORT_OIDCDR=true"
      - "SSL_TRUSTED_SERVER=loginbuddy-demoserver:8443"
    volumes:
      - ./docker-build/add-ons/loginbuddy-sidecar/permissions.policy:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/permissions.policy
      - ./docker-build/add-ons/loginbuddy-sidecar/config.json:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/config.json
      - ./docker-build/add-ons/loginbuddy-sidecar/discovery.json:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/discovery.json

  loginbuddy-oidcdr:
    image: saschazegerman/loginbuddy-oidcdr:latest
    container_name: loginbuddy-oidcdr
    restart: always

#  hazelcast1:
#    image: hazelcast/hazelcast
#    restart: always
#    environment:
#      - "JAVA_OPTS=-Dhazelcast:local:publicAddress=hazelcast1:5701"
#
#  hazelcast2:
#    image: hazelcast/hazelcast
#    restart: always
#    environment:
#      - "JAVA_OPTS=-Dhazelcast:local:publicAddress=hazelcast2:5701"